### PR TITLE
refactor: rework some string lexing to avoid stringLocationsFromString

### PR DESCRIPTION
**Pull request by alangpierce**
BREAKING CHANGE: The DSTRING and SSTRING token types have been removed, and strings now always start with STRING_START and end with STRING_END.

Progress toward https://github.com/decaffeinate/decaffeinate/issues/557

Previously, if you had a string like `"a#{b}c"`, it would lex like this:

DSTRING, INTERPOLATION_START, IDENTIFIER, INTERPOLATION_END, DSTRING

then the `stringLocationsFromString` function would do another pass and change
it to use `STRING_START`, `STRING_CONTENT`, and `STRING_END`. It would detect
the end of a string by finding a `DSTRING` not followed by an
`INTERPOLATION_START`.

Now, instead of that separate pass, we generate `STRING_START`, `STRING_END`,
and `STRING_CONTENT` nodes during the main lexing pass (for single and double
quoted strings) by tracking the type of string on a new `stringStack`. One nice
thing about this change is that there is no longer a distinction between strings
with interpolations and strings without interpolations; they always start with a
`STRING_START` and end with a `STRING_END`.

The plan for future commits is to change herestrings and heregexes to use this
same approach, and then to add a follow-up pass that changes the
`STRING_CONTENT` tokens into something more granular that expresses which parts
of the string should be trimmed.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Looks good! One thing I wonder: is there a good reason to make this not be a breaking change version bump?

**Comment by alangpierce** [comment]
I'm trying to split the refactor up into smaller pieces (maybe 5ish, but we'll see), many of which would be breaking like this one, and it seemed weird to do multiple major version bumps in a row. I thought about trying to do non-breaking refactors and then do all of the breaking things in one small change, but that seems a lot harder. But maybe one of the points of semantic-release is that I shouldn't care so much about version numbers, so I guess I could just trigger a major version release with each one. What do you think?

**Comment by eventualbuddha** [comment]
Yeah, I think we should try to ignore the version number. We can catch up to Chrome if we try hard enough 😊

**Comment by alangpierce** [comment]
Sounds good, I'll do my best. 😄

**Pull request merged**
